#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# LDP Tax Pipeline — Run Script
#
# Usage:
#   ./run.sh                     # normal cloud run
#   ./run.sh --full-refresh-all  # force full recompute
#   LOCAL_MODE=true ./run.sh     # offline test with sample CSV (no cloud)
#
# The script:
#   1. Loads credentials from .env
#   2. Derives storage/warehouse paths (ADLS or local fallback)
#   3. Writes a runtime spark-defaults.conf (credentials + warehouse dir)
#      and points SPARK_CONF_DIR at it so the Spark JVM reads it on startup.
#      This is required because Spark Connect server configs must be set
#      BEFORE the JVM starts — --conf flags only reach the client.
#   4. Generates spark-pipeline.yml from the template (env-var substitution)
#   5. Runs spark-pipelines
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# Pin Java 17 explicitly — cron does not source shell profiles so JAVA_HOME
# would otherwise fall back to the system default (Java 25+), which blocks
# javax.security.auth.Subject.getSubject() used by Hadoop security.
export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
export PATH="${JAVA_HOME}/bin:${PATH}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
export SCRIPT_DIR
cd "$SCRIPT_DIR"

# Capture any values the caller set on the command line BEFORE .env overwrites them
_CLI_LOCAL_MODE="${LOCAL_MODE:-}"

# ── 1. Load .env ──────────────────────────────────────────────────────────────
if [ -f "$SCRIPT_DIR/.env" ]; then
    set -a
    # shellcheck source=.env
    source "$SCRIPT_DIR/.env"
    set +a
else
    echo "[WARN] .env not found — using environment variables already set."
    echo "       Copy .env.example → .env and fill in your credentials."
fi

# Command-line value wins over .env (e.g. LOCAL_MODE=true ./run.sh)
if [ -n "$_CLI_LOCAL_MODE" ]; then
    LOCAL_MODE="$_CLI_LOCAL_MODE"
else
    LOCAL_MODE="${LOCAL_MODE:-false}"
fi

# ── 2. Derived paths ──────────────────────────────────────────────────────────
if [ "$LOCAL_MODE" = "true" ]; then
    LDP_STORAGE_PATH="file://${SCRIPT_DIR}/checkpoints"
    LDP_WAREHOUSE_PATH="file://${SCRIPT_DIR}/spark-warehouse"
    echo "[INFO] LOCAL_MODE=true — using local storage paths."
else
    : "${ADLS_ACCOUNT_NAME:?'ADLS_ACCOUNT_NAME must be set in .env'}"
    : "${ADLS_ACCOUNT_KEY:?'ADLS_ACCOUNT_KEY must be set in .env'}"
    : "${AWS_ACCESS_KEY_ID:?'AWS_ACCESS_KEY_ID must be set in .env'}"
    : "${AWS_SECRET_ACCESS_KEY:?'AWS_SECRET_ACCESS_KEY must be set in .env'}"

    _ADLS_ROOT="abfs://medallion@${ADLS_ACCOUNT_NAME}.dfs.core.windows.net/ldp-tax"
    LDP_STORAGE_PATH="${_ADLS_ROOT}/checkpoints"
    LDP_WAREHOUSE_PATH="${_ADLS_ROOT}/warehouse"
    echo "[INFO] CLOUD MODE — warehouse: ${LDP_WAREHOUSE_PATH}"

    JAR_DIR="${SCRIPT_DIR}/jars"
    if [ ! -d "$JAR_DIR" ] || [ -z "$(ls -A "$JAR_DIR" 2>/dev/null)" ]; then
        echo "[ERROR] Cloud mode requires JARs in ${JAR_DIR}/"
        echo "        Run ./download_jars.sh first."
        exit 1
    fi
    echo "[INFO] Loaded JARs: $(ls "$JAR_DIR"/*.jar | xargs -n1 basename | tr '\n' ' ')"
fi

export LDP_STORAGE_PATH LDP_WAREHOUSE_PATH

# ── 3. Write runtime spark-defaults.conf ──────────────────────────────────────
# Spark reads SPARK_CONF_DIR/spark-defaults.conf before the JVM starts.
# This is the ONLY reliable way to inject credentials into a Spark Connect
# server — --conf flags only reach the client side.
RUNTIME_CONF_DIR="${SCRIPT_DIR}/.spark-conf-runtime"
mkdir -p "$RUNTIME_CONF_DIR"

# Copy the original Spark conf so log4j etc. still work
SYSTEM_CONF_DIR="${SPARK_HOME:-/opt/homebrew/opt/apache-spark/libexec}/conf"
if [ -d "$SYSTEM_CONF_DIR" ]; then
    cp -n "$SYSTEM_CONF_DIR"/* "$RUNTIME_CONF_DIR"/ 2>/dev/null || true
fi

# Write the runtime defaults (overwrites any system defaults)
{
    echo "# ── Generated by run.sh at $(date -Iseconds) ──"
    echo "spark.sql.warehouse.dir        ${LDP_WAREHOUSE_PATH}"
    echo "spark.sql.shuffle.partitions   4"

    if [ "$LOCAL_MODE" != "true" ]; then
        echo "spark.hadoop.fs.s3a.access.key                                          ${AWS_ACCESS_KEY_ID}"
        echo "spark.hadoop.fs.s3a.secret.key                                          ${AWS_SECRET_ACCESS_KEY}"
        echo "spark.hadoop.fs.s3a.endpoint.region                                     ${AWS_REGION:-us-east-1}"
        echo "spark.hadoop.fs.s3a.impl                                                org.apache.hadoop.fs.s3a.S3AFileSystem"
        echo "spark.hadoop.fs.s3a.aws.credentials.provider                            org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
        echo "spark.hadoop.fs.azure.account.auth.type.${ADLS_ACCOUNT_NAME}.dfs.core.windows.net  SharedKey"
        echo "spark.hadoop.fs.azure.account.key.${ADLS_ACCOUNT_NAME}.dfs.core.windows.net        ${ADLS_ACCOUNT_KEY}"
    fi
} > "${RUNTIME_CONF_DIR}/spark-defaults.conf"

export SPARK_CONF_DIR="$RUNTIME_CONF_DIR"
echo "[INFO] Runtime spark-defaults.conf written to ${RUNTIME_CONF_DIR}/"

# ── 4. Generate spark-pipeline.yml from template ──────────────────────────────
python3 - <<'PY'
import os, re

template_path = os.path.join(os.environ["SCRIPT_DIR"], "spark-pipeline-template.yml")
output_path   = os.path.join(os.environ["SCRIPT_DIR"], "spark-pipeline.yml")

with open(template_path) as fh:
    lines = fh.readlines()

def substitute(text):
    def replacer(m):
        key = m.group(1)
        return os.environ.get(key, m.group(0))
    return re.sub(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", replacer, text)

output_lines = []
for line in lines:
    subst = substitute(line)
    # Drop config lines whose value resolved to empty (becomes YAML null)
    if re.match(r"^\s+spark\.\S+:\s*$", subst):
        continue
    output_lines.append(subst)

with open(output_path, "w") as fh:
    fh.writelines(output_lines)

print("[INFO] Generated spark-pipeline.yml from template.")
PY

# ── 5. Activate PySpark environment ───────────────────────────────────────────
VENV="${VENV_PATH:-/Volumes/D/Projects/PysparkLocal/SDP/.venv}"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"
export SPARK_HOME="${SPARK_HOME:-/opt/homebrew/opt/apache-spark/libexec}"

# ── 6. Clean stale state ──────────────────────────────────────────────────────
if [ "$LOCAL_MODE" = "true" ]; then
    # Local mode: always wipe warehouse + metastore (avoids LOCATION_ALREADY_EXISTS)
    echo "[INFO] LOCAL_MODE — cleaning spark-warehouse and metastore_db..."
    rm -rf "${SCRIPT_DIR}/spark-warehouse" "${SCRIPT_DIR}/metastore_db"
else
    # Cloud mode: silver layer uses SCD Type 1 MERGE — warehouse is preserved
    # between runs so incremental upserts accumulate correctly.
    # Only the local metastore_db is wiped (it is rebuilt from ADLS on startup).
    echo "[INFO] CLOUD MODE — wiping metastore_db only (warehouse preserved for SCD1)..."
    rm -rf "${SCRIPT_DIR}/metastore_db"

    # NOTE: ADLS warehouse wipe disabled — silver_tax_records uses MERGE INTO
    # (SCD Type 1). To re-enable full-refresh mode, uncomment the block below
    # and switch 02_silver_tax.sql back to MODE 1.
    #
    # python3 - <<'PY'
    # import base64, hashlib, hmac, os, re, sys
    # from datetime import datetime, timezone
    # from urllib.request import urlopen, Request
    # from urllib.error import HTTPError
    #
    # account   = os.environ["ADLS_ACCOUNT_NAME"]
    # key_b64   = os.environ["ADLS_ACCOUNT_KEY"]
    # warehouse = os.environ["LDP_WAREHOUSE_PATH"]
    #
    # m = re.match(r"abfs://([^@]+)@[^/]+/(.+)", warehouse)
    # if not m:
    #     print(f"[WARN] Cannot parse warehouse path: {warehouse}", file=sys.stderr)
    #     sys.exit(0)
    # filesystem, path = m.group(1), m.group(2)
    #
    # date_str = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S GMT")
    # version  = "2020-02-10"
    # canonicalized_headers  = f"x-ms-date:{date_str}\nx-ms-version:{version}\n"
    # canonicalized_resource = f"/{account}/{filesystem}/{path}\nrecursive:true"
    # string_to_sign = (
    #     "DELETE\n\n\n\n\n\n\n\n\n\n\n\n"
    #     + canonicalized_headers
    #     + canonicalized_resource
    # )
    # sig = base64.b64encode(
    #     hmac.new(base64.b64decode(key_b64), string_to_sign.encode(), hashlib.sha256).digest()
    # ).decode()
    # url = f"https://{account}.dfs.core.windows.net/{filesystem}/{path}?recursive=true"
    # req = Request(url, method="DELETE")
    # req.add_header("x-ms-date",     date_str)
    # req.add_header("x-ms-version",  version)
    # req.add_header("Authorization", f"SharedKey {account}:{sig}")
    # try:
    #     urlopen(req)
    #     print(f"[INFO] Cleared ADLS warehouse: {warehouse}")
    # except HTTPError as e:
    #     if e.code == 404:
    #         print("[INFO] ADLS warehouse path does not exist — starting fresh.")
    #     else:
    #         print(f"[WARN] Azure DELETE returned {e.code}: {e.read().decode()}", file=sys.stderr)
    # PY
fi

# ── 7. Logging setup ──────────────────────────────────────────────────────────
mkdir -p "${SCRIPT_DIR}/logs"
LOG_FILE="${SCRIPT_DIR}/logs/pipeline_$(date +%Y-%m-%d_%H-%M-%S).log"
{
    echo "════════════════════════════════════════════════════════════════"
    echo " LDP Tax Pipeline — started at $(date -Iseconds)"
    echo " LOCAL_MODE  : ${LOCAL_MODE}"
    echo " WAREHOUSE   : ${LDP_WAREHOUSE_PATH}"
    echo " LOG FILE    : ${LOG_FILE}"
    echo "════════════════════════════════════════════════════════════════"
} | tee -a "$LOG_FILE"

# ── 8. Run ────────────────────────────────────────────────────────────────────
CMD=(spark-pipelines run --spec spark-pipeline.yml)
CMD+=("$@")   # forward extra args, e.g. --full-refresh-all

echo "[INFO] Executing: spark-pipelines run --spec spark-pipeline.yml $*" | tee -a "$LOG_FILE"
"${CMD[@]}" 2>&1 | tee -a "$LOG_FILE"
EXIT_CODE=${PIPESTATUS[0]}

# ── 9. Cleanup runtime conf (contains secrets) ────────────────────────────────
rm -rf "$RUNTIME_CONF_DIR"

# ── 10. Result ────────────────────────────────────────────────────────────────
if [ "$EXIT_CODE" -eq 0 ]; then
    echo "[SUCCESS] Pipeline completed at $(date -Iseconds)" | tee -a "$LOG_FILE"
else
    echo "[FAILURE] Pipeline failed (exit $EXIT_CODE) at $(date -Iseconds)" | tee -a "$LOG_FILE"
fi

exit "$EXIT_CODE"
